#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -x
source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/vars.inc

if [ -d $CONFLUENCE_BASE ] ; then
  echo "Confluence $CONFLUENCE_VERSION has already been downloaded."
else
  cd $OPENSHIFT_DEPENDENCIES_DIR
  rm -Rf atlassian-confluence-*
  wget -O $CONFLUENCE_DOWNLOAD_FILE $CONFLUENCE_DOWNLOAD_URL
  tar -xzf $CONFLUENCE_DOWNLOAD_FILE
fi
