#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -x
source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/vars.inc

if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find postgresql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
    echo 1>&2
    exit 5
fi

# Ensure data dir exists.
[ -d $CONFLUENCE_DATA ] || mkdir $CONFLUENCE_DATA

#TODO remove
            #if [ ! -d $CONFLUENCE_DATA ]
            #then
            #    mkdir $CONFLUENCE_DATA
            #    #ln -s $OPENSHIFT_DIY_LOGS $CONFLUENCE_DATA/logs
            #fi

            #TC_DIR=$OPENSHIFT_DATA_DIR/tomcat
            #[ -d $TC_DIR ] || mkdir $TC_DIR
            #rm -Rf $TC_DIR/*

            #mv $CONFLUENCE_BASE/temp $TC_DIR/
            #ln -s $TC_DIR/temp $CONFLUENCE_BASE/temp

            #mv $CONFLUENCE_BASE/work $TC_DIR/
            #ln -s $TC_DIR/work $CONFLUENCE_BASE/work

            #mv $CONFLUENCE_BASE/webapps $TC_DIR/
            #ln -s $TC_DIR/webapps $CONFLUENCE_BASE/webapps

# Set home (data) directory.
echo "confluence.home=${CONFLUENCE_DATA}/" > $CONFLUENCE_BASE/confluence/WEB-INF/classes/confluence-init.properties

# Set variables in server.xml
SERVER_VARS=(
  OPENSHIFT_DIY_IP
  OPENSHIFT_POSTGRESQL_DB_USERNAME
  OPENSHIFT_POSTGRESQL_DB_PASSWORD
  OPENSHIFT_POSTGRESQL_DB_HOST
  OPENSHIFT_POSTGRESQL_DB_PORT
  OPENSHIFT_POSTGRESQL_DB_NAME
)
for x in "${SERVER_VARS[@]}"
do
sed -i s/%${x}%/${!x}/g $OPENSHIFT_REPO_DIR/confluence/server.xml

done

# Copy server.xml to current installation.
cp -f $OPENSHIFT_REPO_DIR/confluence/server.xml \
      $CONFLUENCE_BASE/conf/server.xml

# Copy database driver to current installation.
cp -f $CONFLUENCE_BASE/confluence/WEB-INF/lib/postgresql-* $CONFLUENCE_BASE/lib/
